# main_table = [              
#     "WSQ Frameworks LUT",   
#     # "Area of Training LUT"
#     # "SSIC LUT",           
#     # "Job Roles LUT",      
#     # "Sectors LUT",        
#     # "Edu Of Target Auds LU
#     "Field of Studies LUT", 
#     "Job Levels LUT",       
#     # "Occupations LUT",    
#     # "Qualifications LUT", 
#     # "Sub Sectors LUT",    
#     "Skills Frameworks LUT",
#     "Mapped Skills Competenc
#     # "Framework LUT",      
#     "Outcome Areas LUT",    
#     "Quality Areas LUT",    
#     # "GSC Code LUT",       
#     # "TSC Code LUT",       
#     # "Chart of Accounts LUT
#     # "Skills Code LUT",    
#     # "Key Task LUT",       
#     # "Bank Account LUT",   
#     # "Corporate Hr",       
#     # "Brand",              
#     # "Contact Number",     
#     # "Class Request",      
#     # "Discount Lookup"     
# ]  # End of main_table   
main_table = [     
"Users",
"Training and Assessment Provider",
"TP Branch",
"TP Contact Persons",
"TP Staff",
"Course",
"Course Run",
"Course Session",
"Marketing Info and Brochure",
"Booking Billing Advice Invoice",
"Registration Enrolment Grant",
"Attendance and Assessment",
"Payment Details",
"Payment Breakdown",
"Refund Request",
"Refund Details",
"Credit Note",
"Credit Note Line",
"Credit Note Reasons",
"Trainee",
"Trainer",
"Employer",
"Employer Branch",
"Employer Contact Persons",
"Address",
"Venue with Street and Building",
"Venue with Floor and Unit",
"Venue with Room"
]# End of main_table group1